name: Install test

on:
  push:

permissions:
  contents: read

jobs:
  release:
    name: Install Tuist dependencies using Tuist Registry
    runs-on: macos-15
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          MISE_HTTP_TIMEOUT: 300
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Restore cache
        id: cache-restore
        uses: actions/cache/restore@v4
        with:
          path: |
            .build
          key: ${{ runner.os }}-${{ hashFiles('Package.resolved') }}
          restore-keys: .build
      - name: Install Tuist dependencies
        run: swift package --replace-scm-with-registry resolve
      - name: Save cache
        id: cache-save
        uses: actions/cache/save@v4
        with:
          path: |
            .build
          key: ${{ steps.cache-restore.outputs.cache-primary-key }}
