name: Install test

on:
  push:

permissions:
  contents: read

jobs:
  release:
    name: Install Tuist dependencies using Tuist Registry
    runs-on: macos-15
    timeout-minutes: 20
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        env:
          MISE_HTTP_TIMEOUT: 300
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Install Tuist dependencies
        run: swift package --replace-scm-with-registry resolve
